# Reproduce locally by running:
# ```r
# pak::pak(c("any::rmarkdown", "any::usethis", "any::allcontributors", "."))
# writeLines(
#   knitr::knit_expand(
#     "README.Rmd",
#     packagename = read.dcf("DESCRIPTION", "Package"),
#     gh_repo = usethis:::github_remote_list()$repo_spec
#   ),
#   "README_expanded.Rmd"
# )
# rmarkdown::render(
#   "README_expanded.Rmd",
#   output_file = "README.md",
#   output_dir = "."
# )
# unlink("README_expanded.Rmd")
# ```
name: render-readme

# Controls when the action will run. Triggers include:
#
# - button trigger from github action page
# - on changes to readme.Rmd

on:
  workflow_dispatch:
  push:
    paths:
      - 'README.Rmd'
      - '.github/workflows/render_readme.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  render-readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repos
        uses: actions/checkout@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rmarkdown, any::allcontributors, local::., any::ggplot2

      - name: Update contributors
        if: github.ref == 'refs/heads/main'
        run: allcontributors::add_contributors(format = "text")
        shell: Rscript {0}

      - name: Compile the readme
        run: |
          writeLines(
            knitr::knit_expand(
              "README.Rmd",
              packagename = read.dcf("DESCRIPTION", "Package"),
              gh_repo = Sys.getenv("GITHUB_REPOSITORY")
            ),
            "README_expanded.Rmd"
          )
          rmarkdown::render(
            "README_expanded.Rmd",
            output_file = "README.md",
            output_dir = "."
          )
        shell: Rscript {0}

      - name: Upload README.md as an artifact
        uses: actions/upload-artifact@v5
        with:
          name: readme
          path: README.md

      - name: Create Pull Request
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Automatic README update"
          title: "Update README"
          body: "This is an automated pull request to update the README."
          branch: "update-readme-${{ github.run_number }}"
          labels: "documentation"
          add-paths: |
            README.Rmd
            README.md
          token: ${{ steps.generate_token.outputs.token }}
